<?xml version="1.0"?>
<!DOCTYPE ESGI [     
<!ELEMENT classrooms (classroom+)>
<!ELEMENT classroom (#PCDATA) >
<!ELEMENT proutroom (prout)>
]>


<classrooms>
<classroom>ABC</classroom>
<classroom>IABD</classroom>
<classroom>MOC</classroom>
<classroom>BRO</classroom>
</classrooms>